# -*- coding:utf-8 -*-
# coding=<utf8>


# Оперативная память
ROM_form_factors = ['SIMM', 'DIMM', 'FB-DIMM', 'SODIMM', 'MicroDIMM', 'RIMM']
ROM_type=['DDR','DDR2','DDR3','RDRAM','SDRAM']
ROM_firms = ['Corsair', 'Crucial', 'Foxline', 'G.SKILL', 'HP', 'Hynix', 'Kingmax', 'Kingston', 'Patriot Memory', 'Samsung', 'Silicon Power', 'Transcend', 'Acer', 'ADATA', 'AMD', 'Apacer', 'Apple', 'Ceon', 'Chaintech', 'Cisco', 'DELL', 'Digma', 'Elixir', 'EUDAR', 'Exceleram', 'Fujitsu', 'Fujitsu-Siemens', 'Geil', 'GoodRAM', 'Lenovo', 'Micron', 'Mushkin', 'Nanya', 'NCP', 'OCZ', 'PQI', 'Qumo', 'Sony', 'Spectek', 'Sun Microsystems', 'Super Talent', 'TakeMS', 'Team Group', 'Toshiba', 'TwinMOS']
ROM_V = ['128','512','1024','2048','4096','8192']
ROM_clock_frequency = ['100 MHz', '1000 MHz', '1066 MHz', '1100 MHz', '1200 MHz', '133 MHz', '1333 MHz', '1375 MHz', '1600 MHz', '1750 MHz', '1800 MHz', '1866 MHz', '200 MHz', '2000 MHz', '2133 MHz', '2200 MHz', '2250 MHz', '2300 MHz', '2400 MHz', '2600 MHz', '266 MHz', '2666 MHz', '2800 MHz', '333 MHz', '400 MHz', '500 MHz', '533 MHz', '66 MHz', '667 MHz', '750 MHz', '800 MHz']
ROM_throughput = ['10600 Мб/с', '10660 Мб/с', '10666 Мб/с', '10700 Мб/с', '12800 Мб/с', '14000 Мб/с', '14400 Мб/с', '14900 Мб/с', '15000 Мб/с', '1600 Мб/с', '16000 Мб/с', '17000 Мб/с', '17066 Мб/с', '17600 Мб/с', '18000 Мб/с', '18400 Мб/с', '19200 Мб/с', '20800 Мб/с', '2100 Мб/с', '21300 Мб/с', '21330 Мб/с', '22400 Мб/с', '2700 Мб/с', '3200 Мб/с', '4000 Мб/с', '4200 Мб/с', '4300 Мб/с', '5300 Мб/с', '6000 Мб/с', '6400 Мб/с', '8000 Мб/с', '8500 Мб/с', '8800 Мб/с', '9600 Мб/с']
# Кулеры
Cooler_firms = ['Arctic Cooling', 'Cooler Master', 'Corsair', 'Deepcool', 'GlacialTech', 'Ice Hammer', 'Noctua', 'Scythe', 'Thermalright', 'Thermaltake', 'Titan', 'Zalman', '', '@Lux', 'AeroCool', 'AIC', 'Akasa', 'Alpenfoehn', 'Antec', 'ASUS', 'Auras', 'AVC', 'be quiet!', 'BitFenix', 'Chieftec', 'Coolcox', 'Cooler Tech', 'CoolerBoss', 'CROWN', 'DELL', 'DELTA', 'Dynatron', 'Ebmpapst', 'Enermax', 'Espada', 'Evercool', 'Exegate', 'Floston', 'Foxconn', 'G.SKILL', 'GELID Solutions', 'Gembird', 'GRAND', 'Gresso', 'Intel', 'Jetart', 'Kinghun', 'Koolance', 'larkooler', 'LEPA', 'LogicPower', 'Manhattan', 'Maxtron', 'NANOXIA', 'Nexus', 'NOISEBLOCKER', 'NZXT', 'OCZ', 'Pangu', 'PCcooler', 'Phanteks', 'Prolimatech', 'Revoltec', 'SilenX', 'SilverStone', 'Speeze', 'Spire', 'Spiriter', 'STM', 'SUNON', 'Supermicro', 'Sven', 'ThermalFly', 'Vantec', 'Vizo', 'Xigmatek', 'Xilence', 'YATE LOON', 'ZAWARD', 'ZEROtherm']
Cooler_destination = ['для видеокарты', 'для винчестера', 'для корпуса', 'для памяти', 'для процессора', 'для чипсета']
Cooler_sockets = ['Socket A(462)/370', 'Socket AM2', 'Socket AM2+', 'Socket AM3/AM3+/FM1', 'Socket FM2', 'Socket F/С32', 'Socket F+', 'Socket G34', 'Socket 754', 'Socket 939', 'Socket 940', 'Socket 478', 'Socket 775', 'Socket 1155/1156', 'Socket 1366', 'Socket 1567', 'Socket 2011', 'Socket 603', 'Socket 604', 'Socket 771']
Cooler_connector = ['3-pin', '4-pin Molex', '4-pin PWM']
# Хранилища данных
Storage_firms = ['ADATA', 'Hitachi', 'Intel', 'Kingston', 'OCZ', 'Plextor', 'Seagate', 'Silicon Power', 'Synology', 'Toshiba', 'Transcend', 'Western Digital']
Storage_form_factor = ['1.8"', '2.5"', '3.5"']
Storage_interfaces = ['SATA', 'IDE', 'USB', 'FireWire', 'PCI-E', 'SCSI', 'SAS', 'eSATA', 'FireWir e800', 'Fibre Channel', 'Thunderbolt', 'HSDL', 'mSata', 'Ethernet', 'ExpressCard/34', 'ZIF 40 pin', 'mini PCI-E']
Storage_rpm = ['3600 rpm', '4200 rpm', '5200 rpm', '5400 rpm', '5700 rpm', '5900 rpm', '7200 rpm', '10000 rpm', '10025 rpm', '10075 rpm', '10500 rpm', '15000 rpm']
# Колонки и т.п.
Acoustics_firms = ['Creative', 'Defender', 'Dialog', 'Edifier', 'Genius', 'Harman/Kardon', 'JBL', 'JetBalance', 'Logitech', 'Microlab', 'Sven', 'TopDevice', '', '4U', 'A4Tech', 'ACME', 'Acoustic Energy', 'AirTone', 'Altec Lansing', 'Arctic', 'ASUS', 'AVE', 'BBK', 'Bliss', 'Bose', 'Bowers & Wilkins', 'Canyon', 'CBR', 'Cirkuit Planet', 'Codegen SuperPower', 'Comep', 'Cooler Master', 'Corsair', 'CROWN', 'DELL', 'Delux', 'DeTech', 'DIGITUS', 'Divoom', 'DTS', 'Easy Touch', 'ENDEVER', 'Enzatec', 'Espada', 'F&D', 'Fujitsu', 'Fujitsu-Siemens', 'Gear Head', 'Gembird', 'Gemix', 'GIGABYTE', 'GoldenField', 'GRAND', 'Grundig', 'HAMA', 'Hardity', 'Hercules', 'HP', 'iLuv', 'Jet.A', 'k-3', 'Kinghun', 'Klipsch', 'KME', 'Konoos', 'Kreolz', 'KWorld', 'Labtec', 'LOGICFOX', 'Manhattan', 'MB Sound', 'Media-Tech', 'Mobiledata', 'Modecom', 'MSI', 'NAKATOMI', 'NeoDrive', 'ORIENT', 'Ozaki', 'Perfeo', 'Philips', 'Prestigio', 'Ritmix', 'Samsung', 'Sanyoo', 'Scythe', 'SmartTrack', 'SonicGear', 'Sony', 'Sound Pro', 'Soundtronix', 'SPEED', 'SPEEDLINK', 'Sweex', 'T&D', "T'nB", 'Targa', 'Titan', 'Trust', 'UNITY', 'Velton', 'Vicsone', 'VIGOOLE', 'X5Tech', 'XtremeMac', 'Yubz', 'Zalman']
Acoustics_type = ['1.0', '2.0', '2.1', '4.1', '5.0', '5.1', '6.1']
# Телефоны
Telephone_firms = [u'Senao', u'\u0414\u0438\u0430\u043b\u043e\u0433', u'SUPRA', u'Voxtel', u'SwissVoice', u'\u041f\u0430\u043b\u0438\u0445\u0430', u'General Electric', u'Horizont', u'\u041a\u041e\u041c\u041c\u0422\u0415\u041b', u'LG', u'Goodwin', u'Akai', u'Bang & Olufsen', u'ALCOM', u'Plantronics', u'Siemens', u'\u041c\u042d\u041b\u0422', u'Komtel', u'Ritmix', u'Philips', u'Motorola', u'BBK', u'Alcatel', u'Intego', u'\u0412\u0435\u043a\u0442\u043e\u0440', u'Rolsen', u'Gigaset', u'Sagem', u'Euroline', u'\u0422\u0435\u043b\u0444\u043e\u043d', u'\u0424\u0430\u044d\u0442\u043e\u043d', u'\u041a\u043e\u043b\u0438\u0431\u0440\u0438', u'teleGEO', u'\u0422\u0435\u043b\u043b\u0443\u0440', u'LG-Ericsson', u'Switel', u'LG-Nortel', u'Binatone', u'Soul Electronics', u'TeXet', u'Premier', u'Unitel City', u'Orion', u'Rotex', u'\u0422\u0435\u043b\u0442\u0430', u'Shivaki', u'Panasonic']
Telephone_frequency = ['1880-1900 MHz', '240-390 MHz', '307-343 MHz', '31-40 MHz', '900/2400 MHz']
# Батарейки и аккумуляторы
Battery_firms = ['Energizer','Duracell']
Battery_type = ['AA', 'AAA', 'C', 'D', 'PP3 (Krona)']

Optical_Drive_firms = ['3Q', 'Apple', 'ASUS', 'HP', 'Lenovo', 'LG', 'LITE-ON', 'Pioneer', 'Plextor', 'Sony NEC Optiarc', 'Toshiba Samsung Storage Technology', 'Transcend', 'Acer', 'Buffalo', 'Canyon', 'DELL', 'Foxconn', 'Fujitsu', 'Intel', 'Iomega', 'Kreolz', 'Lacie', 'NU', 'ONEXT', 'Panasonic', 'Rovermate', 'Sun Microsystems', 'Supermicro', 'TEAC']
Optical_Drive_type = ['BD-RE', 'BD-ROM', 'BD-ROM/DVD RW', 'BD-ROM/HD DVD-ROM/DVD RW', 'CD-ROM', 'CD-RW', 'DVD RW', 'DVD RW DL', 'DVD-ROM', 'DVD/CD-RW']
Optical_Drive_interfaces = ['eSATA/USB', 'Ethernet/USB', 'FireWire', 'IDE', 'SATA', 'USB']

Network_equipment_firms = [u'Ubiquiti', u'', u'Nano', u'SIVVA', u'3COM', u'Huawei', u'Winstars', u'CCK', u'HAMA', u'Compex', u'Linkpro', u'Galaxy Innovations', u'Allied Telesyn', u'S-iTECH', u'Level One', u'Skylink', u'Buro', u'SPEEDLINK', u'GIGABYTE', u'DIGITUS', u'Rovermate', u'GetNet', u'Normann', u'Porto', u'EUSSO', u'LOGICFOX', u'Mobiledata', u'Cisco', u'2N', u'Z-Com', u'Pentagram', u'Carelink', u'Globo', u'Edimax', u'TRENDnet', u'Alwise', u'Sweex', u'CYBER', u'QTECH', u'Upvel', u'Fortinet', u'Qbiq', u'Novatel Wireless', u'eXtreme', u'Petatel', u'\u041c\u0422\u0421', u'HP', u'Proxim', u'Espada', u'DrayTek', u'Eye-Fi', u'Cyclone', u'Emtec', u'Option', u'STLab', u'Yota', u'AMX', u'X-Micro', u'Sony', u'Throw', u'EnGenius', u'Motorola', u'Linksys', u'Samsung', u'D-link', u'U.S.Robotics', u'Asotel', u'Qumo', u'Deppa', u'NCENTRA', u'Loopcomm', u'Western Digital', u'Buffalo', u'ORIENT', u'Planet', u'MOXA', u'Seowon Intech', u'SIYOTEAM', u'Nortel', u'CBR', u'Terminal Equipment', u'LogicPower', u'ASUS', u'BandRich', u'Opticum', u'\u0422\u041e\u041d\u041a', u'Novacom Wireless', u'Senao', u'EDUP', u'Vertex', u'Multico', u'Alfa Network', u'Creative', u'Genius', u'NeoDrive', u'C-net', u'SMC', u'X-NET', u'Intellinet', u'Gemix', u'Arctic', u'OXO Electronics', u'Popcorn Hour', u'3Q', u'Symanitron', u'BBK', u'Intel', u'ZTE', u'Palmexx', u'Powchip', u'Grand-X', u'Sparklan', u'Euroline', u'TP-LINK', u'Media-Tech', u'Edge-Core', u'x3', u'MicroNet', u'Welltech', u'DT-Link', u'Belkin', u'Surecom', u'Canyon', u'NETGEAR', u'Panasonic', u'Mobidick', u'Tenda', u'MSI', u'Dynamode', u'LEXAND', u'Pheenet', u'Brickcom', u'CLiPtec', u'AirTies', u'ZyXEL', u'SerteC', u'LG', u'Juniper', u'Acorp', u'Crestron', u'Kreolz', u'AirLive', u'eVidence', u'REPOTEC', u'Promate', u'Sandisk', u'Philips', u'InterStep', u'Egreat', u'Alcatel', u'BEWARD', u'DELL', u'AudioCodes', u'Netis', u'Encore', u'Sitecom', u'ARC Wireless', u'Apple', u'Gemtek', u'EWEL', u'Gembird', u'Dynamix', u'MikroTik', u'Trust']
Network_equipment_type = ['Router','Switch','AP','Repeater','Smart Switch']
Network_equipment_WiFi_type = ['802.11a', '802.11a/b/g', '802.11ac', '802.11b', '802.11g', '802.11n']

Printer_firm = ['Brother', 'Canon', 'Epson', 'HP', 'Kyocera', 'Lexmark', 'OKI', 'Panasonic', 'Ricoh', 'Samsung', 'Toshiba', 'Xerox', 'DELL', 'Develop', 'Flora', 'Fujifilm', 'Gestetner', 'HiTi', 'KIP', 'Konica Minolta', 'Lomond', 'MB', 'Mimaki', 'Mitsubishi Electric', 'Mutoh', 'Oce', 'Pantum', 'Philips', 'Polaroid', 'Riso', 'Roland', 'ROWE', 'Seiko', 'Sharp', 'Shinco', 'Sony']

# [b.strip() for b in a.strip().split('\n')]